name: Slack Notification

on:
  push:
    branches:
      - main
      
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
    - name: Send Slack notification
      uses: 8398a7/action-slack@v3
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: 'good'
        channel: '#general'
        message: 'hi'
