name: Enviar mensagem para o Slack
on: [push]
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
    - name: Send Slack notification
      uses: 8398a7/action-slack@v3
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        channel: '#general'
        message: 'hello'
