name: Enviar mensagem para o Slack
on: [push]
jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
    - name: Enviar mensagem
      uses: rtCamp/action-slack-notify@v2.3.0
      env:
        SLACK_CHANNEL: 'C04RYP6CVNF'
        SLACK_BOT_TOKEN: 'xoxp-83394036917-4596943277793-4895553710321-e798cced52d8a2c85c6fcdb420b54a75'
      with:
        message: "Olá, Slack!"
