name: Slack Notification

on:
  pull_request:
    types: [closed]

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
    - name: Send Slack notification
      uses: 8398a7/action-slack@v3
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        channel: '#general'
        message: 'Pull request merged: ${{ github.event.pull_request.title }}'
