name: Enviar mensagem para o Slack
on: [push]
jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
    - name: Enviar mensagem
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: 'C04RYP6CVNF'
        SLACK_BOT_TOKEN: 'T2FBL12SZ/B04S1BFK2JG/HKa8Z6PMCYfrPYsUdnwmGrX7'
      with:
        message: "Olá, Slack!"
